export enum CountryCodeEnum {
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BQ = 'BQ',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BV = 'BV',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CW = 'CW',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  EH = 'EH',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GF = 'GF',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GP = 'GP',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HM = 'HM',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SX = 'SX',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TF = 'TF',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  UM = 'UM',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  YE = 'YE',
  YT = 'YT',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
}

export const COUNTRY_CODE_LABELS: Record<CountryCodeEnum, string> = {
  [CountryCodeEnum.AD]: 'Andorra',
  [CountryCodeEnum.AE]: 'Emirados Árabes Unidos',
  [CountryCodeEnum.AF]: 'Afeganistão',
  [CountryCodeEnum.AG]: 'Antígua e Barbuda',
  [CountryCodeEnum.AI]: 'Anguilla',
  [CountryCodeEnum.AL]: 'Albânia',
  [CountryCodeEnum.AM]: 'Armênia',
  [CountryCodeEnum.AO]: 'Angola',
  [CountryCodeEnum.AQ]: 'Antártida',
  [CountryCodeEnum.AR]: 'Argentina',
  [CountryCodeEnum.AS]: 'Samoa Americana',
  [CountryCodeEnum.AT]: 'Áustria',
  [CountryCodeEnum.AU]: 'Austrália',
  [CountryCodeEnum.AW]: 'Aruba',
  [CountryCodeEnum.AX]: 'Ilhas Aland',
  [CountryCodeEnum.AZ]: 'Azerbaijão',
  [CountryCodeEnum.BA]: 'Bósnia e Herzegovina',
  [CountryCodeEnum.BB]: 'Barbados',
  [CountryCodeEnum.BD]: 'Bangladesh',
  [CountryCodeEnum.BE]: 'Bélgica',
  [CountryCodeEnum.BF]: 'Burkina Faso',
  [CountryCodeEnum.BG]: 'Bulgária',
  [CountryCodeEnum.BH]: 'Bahrein',
  [CountryCodeEnum.BI]: 'Burundi',
  [CountryCodeEnum.BJ]: 'Benim',
  [CountryCodeEnum.BL]: 'São Bartolomeu',
  [CountryCodeEnum.BM]: 'Bermudas',
  [CountryCodeEnum.BN]: 'Brunei',
  [CountryCodeEnum.BO]: 'Bolívia',
  [CountryCodeEnum.BQ]: 'Caribe Neerlandês',
  [CountryCodeEnum.BR]: 'Brasil',
  [CountryCodeEnum.BS]: 'Bahamas',
  [CountryCodeEnum.BT]: 'Butão',
  [CountryCodeEnum.BV]: 'Ilha Bouvet',
  [CountryCodeEnum.BW]: 'Botsuana',
  [CountryCodeEnum.BY]: 'Belarus',
  [CountryCodeEnum.BZ]: 'Belize',
  [CountryCodeEnum.CA]: 'Canadá',
  [CountryCodeEnum.CC]: 'Ilhas Cocos',
  [CountryCodeEnum.CD]: 'República Democrática do Congo',
  [CountryCodeEnum.CF]: 'República Centro-Africana',
  [CountryCodeEnum.CG]: 'República do Congo',
  [CountryCodeEnum.CH]: 'Suíça',
  [CountryCodeEnum.CI]: 'Costa do Marfim',
  [CountryCodeEnum.CK]: 'Ilhas Cook',
  [CountryCodeEnum.CL]: 'Chile',
  [CountryCodeEnum.CM]: 'Camarões',
  [CountryCodeEnum.CN]: 'China',
  [CountryCodeEnum.CO]: 'Colômbia',
  [CountryCodeEnum.CR]: 'Costa Rica',
  [CountryCodeEnum.CU]: 'Cuba',
  [CountryCodeEnum.CV]: 'Cabo Verde',
  [CountryCodeEnum.CW]: 'Curaçao',
  [CountryCodeEnum.CX]: 'Ilha Christmas',
  [CountryCodeEnum.CY]: 'Chipre',
  [CountryCodeEnum.CZ]: 'Tchéquia',
  [CountryCodeEnum.DE]: 'Alemanha',
  [CountryCodeEnum.DJ]: 'Djibuti',
  [CountryCodeEnum.DK]: 'Dinamarca',
  [CountryCodeEnum.DM]: 'Dominica',
  [CountryCodeEnum.DO]: 'República Dominicana',
  [CountryCodeEnum.DZ]: 'Argélia',
  [CountryCodeEnum.EC]: 'Equador',
  [CountryCodeEnum.EE]: 'Estônia',
  [CountryCodeEnum.EG]: 'Egito',
  [CountryCodeEnum.EH]: 'Saara Ocidental',
  [CountryCodeEnum.ER]: 'Eritreia',
  [CountryCodeEnum.ES]: 'Espanha',
  [CountryCodeEnum.ET]: 'Etiópia',
  [CountryCodeEnum.FI]: 'Finlândia',
  [CountryCodeEnum.FJ]: 'Fiji',
  [CountryCodeEnum.FK]: 'Ilhas Malvinas',
  [CountryCodeEnum.FM]: 'Micronésia',
  [CountryCodeEnum.FO]: 'Ilhas Faroé',
  [CountryCodeEnum.FR]: 'França',
  [CountryCodeEnum.GA]: 'Gabão',
  [CountryCodeEnum.GB]: 'Reino Unido',
  [CountryCodeEnum.GD]: 'Granada',
  [CountryCodeEnum.GE]: 'Geórgia',
  [CountryCodeEnum.GF]: 'Guiana Francesa',
  [CountryCodeEnum.GG]: 'Guernsey',
  [CountryCodeEnum.GH]: 'Gana',
  [CountryCodeEnum.GI]: 'Gibraltar',
  [CountryCodeEnum.GL]: 'Groenlândia',
  [CountryCodeEnum.GM]: 'Gâmbia',
  [CountryCodeEnum.GN]: 'Guiné',
  [CountryCodeEnum.GP]: 'Guadalupe',
  [CountryCodeEnum.GQ]: 'Guiné Equatorial',
  [CountryCodeEnum.GR]: 'Grécia',
  [CountryCodeEnum.GS]: 'Geórgia do Sul e Ilhas Sandwich do Sul',
  [CountryCodeEnum.GT]: 'Guatemala',
  [CountryCodeEnum.GU]: 'Guam',
  [CountryCodeEnum.GW]: 'Guiné-Bissau',
  [CountryCodeEnum.GY]: 'Guiana',
  [CountryCodeEnum.HK]: 'Hong Kong',
  [CountryCodeEnum.HM]: 'Ilhas Heard e McDonald',
  [CountryCodeEnum.HN]: 'Honduras',
  [CountryCodeEnum.HR]: 'Croácia',
  [CountryCodeEnum.HT]: 'Haiti',
  [CountryCodeEnum.HU]: 'Hungria',
  [CountryCodeEnum.ID]: 'Indonésia',
  [CountryCodeEnum.IE]: 'Irlanda',
  [CountryCodeEnum.IL]: 'Israel',
  [CountryCodeEnum.IM]: 'Ilha de Man',
  [CountryCodeEnum.IN]: 'Índia',
  [CountryCodeEnum.IO]: 'Território Britânico do Oceano Índico',
  [CountryCodeEnum.IQ]: 'Iraque',
  [CountryCodeEnum.IR]: 'Irã',
  [CountryCodeEnum.IS]: 'Islândia',
  [CountryCodeEnum.IT]: 'Itália',
  [CountryCodeEnum.JE]: 'Jersey',
  [CountryCodeEnum.JM]: 'Jamaica',
  [CountryCodeEnum.JO]: 'Jordânia',
  [CountryCodeEnum.JP]: 'Japão',
  [CountryCodeEnum.KE]: 'Quênia',
  [CountryCodeEnum.KG]: 'Quirguistão',
  [CountryCodeEnum.KH]: 'Camboja',
  [CountryCodeEnum.KI]: 'Kiribati',
  [CountryCodeEnum.KM]: 'Comores',
  [CountryCodeEnum.KN]: 'São Cristóvão e Névis',
  [CountryCodeEnum.KP]: 'Coreia do Norte',
  [CountryCodeEnum.KR]: 'Coreia do Sul',
  [CountryCodeEnum.KW]: 'Kuwait',
  [CountryCodeEnum.KY]: 'Ilhas Cayman',
  [CountryCodeEnum.KZ]: 'Cazaquistão',
  [CountryCodeEnum.LA]: 'Laos',
  [CountryCodeEnum.LB]: 'Líbano',
  [CountryCodeEnum.LC]: 'Santa Lúcia',
  [CountryCodeEnum.LI]: 'Liechtenstein',
  [CountryCodeEnum.LK]: 'Sri Lanka',
  [CountryCodeEnum.LR]: 'Libéria',
  [CountryCodeEnum.LS]: 'Lesoto',
  [CountryCodeEnum.LT]: 'Lituânia',
  [CountryCodeEnum.LU]: 'Luxemburgo',
  [CountryCodeEnum.LV]: 'Letônia',
  [CountryCodeEnum.LY]: 'Líbia',
  [CountryCodeEnum.MA]: 'Marrocos',
  [CountryCodeEnum.MC]: 'Mônaco',
  [CountryCodeEnum.MD]: 'Moldova',
  [CountryCodeEnum.ME]: 'Montenegro',
  [CountryCodeEnum.MF]: 'São Martinho',
  [CountryCodeEnum.MG]: 'Madagascar',
  [CountryCodeEnum.MH]: 'Ilhas Marshall',
  [CountryCodeEnum.MK]: 'Macedônia do Norte',
  [CountryCodeEnum.ML]: 'Mali',
  [CountryCodeEnum.MM]: 'Myanmar',
  [CountryCodeEnum.MN]: 'Mongólia',
  [CountryCodeEnum.MO]: 'Macau',
  [CountryCodeEnum.MP]: 'Ilhas Marianas do Norte',
  [CountryCodeEnum.MQ]: 'Martinica',
  [CountryCodeEnum.MR]: 'Mauritânia',
  [CountryCodeEnum.MS]: 'Montserrat',
  [CountryCodeEnum.MT]: 'Malta',
  [CountryCodeEnum.MU]: 'Maurício',
  [CountryCodeEnum.MV]: 'Maldivas',
  [CountryCodeEnum.MW]: 'Malawi',
  [CountryCodeEnum.MX]: 'México',
  [CountryCodeEnum.MY]: 'Malásia',
  [CountryCodeEnum.MZ]: 'Moçambique',
  [CountryCodeEnum.NA]: 'Namíbia',
  [CountryCodeEnum.NC]: 'Nova Caledônia',
  [CountryCodeEnum.NE]: 'Níger',
  [CountryCodeEnum.NF]: 'Ilha Norfolk',
  [CountryCodeEnum.NG]: 'Nigéria',
  [CountryCodeEnum.NI]: 'Nicarágua',
  [CountryCodeEnum.NL]: 'Países Baixos',
  [CountryCodeEnum.NO]: 'Noruega',
  [CountryCodeEnum.NP]: 'Nepal',
  [CountryCodeEnum.NR]: 'Nauru',
  [CountryCodeEnum.NU]: 'Niue',
  [CountryCodeEnum.NZ]: 'Nova Zelândia',
  [CountryCodeEnum.OM]: 'Omã',
  [CountryCodeEnum.PA]: 'Panamá',
  [CountryCodeEnum.PE]: 'Peru',
  [CountryCodeEnum.PF]: 'Polinésia Francesa',
  [CountryCodeEnum.PG]: 'Papua-Nova Guiné',
  [CountryCodeEnum.PH]: 'Filipinas',
  [CountryCodeEnum.PK]: 'Paquistão',
  [CountryCodeEnum.PL]: 'Polônia',
  [CountryCodeEnum.PM]: 'São Pedro e Miquelão',
  [CountryCodeEnum.PN]: 'Ilhas Pitcairn',
  [CountryCodeEnum.PR]: 'Porto Rico',
  [CountryCodeEnum.PS]: 'Palestina',
  [CountryCodeEnum.PT]: 'Portugal',
  [CountryCodeEnum.PW]: 'Palau',
  [CountryCodeEnum.PY]: 'Paraguai',
  [CountryCodeEnum.QA]: 'Catar',
  [CountryCodeEnum.RE]: 'Reunião',
  [CountryCodeEnum.RO]: 'Romênia',
  [CountryCodeEnum.RS]: 'Sérvia',
  [CountryCodeEnum.RU]: 'Rússia',
  [CountryCodeEnum.RW]: 'Ruanda',
  [CountryCodeEnum.SA]: 'Arábia Saudita',
  [CountryCodeEnum.SB]: 'Ilhas Salomão',
  [CountryCodeEnum.SC]: 'Seicheles',
  [CountryCodeEnum.SD]: 'Sudão',
  [CountryCodeEnum.SE]: 'Suécia',
  [CountryCodeEnum.SG]: 'Singapura',
  [CountryCodeEnum.SH]: 'Santa Helena',
  [CountryCodeEnum.SI]: 'Eslovênia',
  [CountryCodeEnum.SJ]: 'Svalbard e Jan Mayen',
  [CountryCodeEnum.SK]: 'Eslováquia',
  [CountryCodeEnum.SL]: 'Serra Leoa',
  [CountryCodeEnum.SM]: 'San Marino',
  [CountryCodeEnum.SN]: 'Senegal',
  [CountryCodeEnum.SO]: 'Somália',
  [CountryCodeEnum.SR]: 'Suriname',
  [CountryCodeEnum.SS]: 'Sudão do Sul',
  [CountryCodeEnum.ST]: 'São Tomé e Príncipe',
  [CountryCodeEnum.SV]: 'El Salvador',
  [CountryCodeEnum.SX]: 'Sint Maarten',
  [CountryCodeEnum.SY]: 'Síria',
  [CountryCodeEnum.SZ]: 'Essuatíni',
  [CountryCodeEnum.TC]: 'Ilhas Turcas e Caicos',
  [CountryCodeEnum.TD]: 'Chade',
  [CountryCodeEnum.TF]: 'Terras Austrais e Antárticas Francesas',
  [CountryCodeEnum.TG]: 'Togo',
  [CountryCodeEnum.TH]: 'Tailândia',
  [CountryCodeEnum.TJ]: 'Tadjiquistão',
  [CountryCodeEnum.TK]: 'Toquelau',
  [CountryCodeEnum.TL]: 'Timor-Leste',
  [CountryCodeEnum.TM]: 'Turcomenistão',
  [CountryCodeEnum.TN]: 'Tunísia',
  [CountryCodeEnum.TO]: 'Tonga',
  [CountryCodeEnum.TR]: 'Turquia',
  [CountryCodeEnum.TT]: 'Trinidad e Tobago',
  [CountryCodeEnum.TV]: 'Tuvalu',
  [CountryCodeEnum.TW]: 'Taiwan',
  [CountryCodeEnum.TZ]: 'Tanzânia',
  [CountryCodeEnum.UA]: 'Ucrânia',
  [CountryCodeEnum.UG]: 'Uganda',
  [CountryCodeEnum.UM]: 'Ilhas Menores Distantes dos Estados Unidos',
  [CountryCodeEnum.US]: 'Estados Unidos',
  [CountryCodeEnum.UY]: 'Uruguai',
  [CountryCodeEnum.UZ]: 'Uzbequistão',
  [CountryCodeEnum.VA]: 'Vaticano',
  [CountryCodeEnum.VC]: 'São Vicente e Granadinas',
  [CountryCodeEnum.VE]: 'Venezuela',
  [CountryCodeEnum.VG]: 'Ilhas Virgens Britânicas',
  [CountryCodeEnum.VI]: 'Ilhas Virgens dos Estados Unidos',
  [CountryCodeEnum.VN]: 'Vietnã',
  [CountryCodeEnum.VU]: 'Vanuatu',
  [CountryCodeEnum.WF]: 'Wallis e Futuna',
  [CountryCodeEnum.WS]: 'Samoa',
  [CountryCodeEnum.YE]: 'Iêmen',
  [CountryCodeEnum.YT]: 'Mayotte',
  [CountryCodeEnum.ZA]: 'África do Sul',
  [CountryCodeEnum.ZM]: 'Zâmbia',
  [CountryCodeEnum.ZW]: 'Zimbábue',
};
