name: "5 - Release promote"

on:
  pull_request:
    types: closed
    branches: 'main'

jobs:
  app:
    uses: itau-corp/itau-up2-nested-reusable-nodejs-s3/.github/workflows/release.yml@v2-stk-wk
    secrets: inherit
